CREATE TABLE PLANNER_SESSIONS
(
    ID             BIGSERIAL      PRIMARY KEY,
    SESSION_TOKEN  VARCHAR(64)    NOT NULL UNIQUE,
    USER_ID        BIGINT         NOT NULL REFERENCES USERS(ID),
    EXPLORATION_ID VARCHAR(50),
    TITLE          VARCHAR(255),
    CREATED_AT     TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    UPDATED_AT     TIMESTAMPTZ    NOT NULL DEFAULT NOW()
);

CREATE INDEX IDX_PLANNER_SESSIONS_USER_ID ON PLANNER_SESSIONS(USER_ID);

CREATE TABLE PLANNER_MESSAGES
(
    ID         BIGSERIAL    PRIMARY KEY,
    SESSION_ID BIGINT       NOT NULL REFERENCES PLANNER_SESSIONS(ID),
    ROLE       VARCHAR(20)  NOT NULL,
    CONTENT    TEXT         NOT NULL,
    CREATED_AT TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IDX_PLANNER_MESSAGES_SESSION_ID ON PLANNER_MESSAGES(SESSION_ID);

CREATE TABLE PLANNER_APPLIED_ITINERARIES
(
    ID          BIGSERIAL    PRIMARY KEY,
    SESSION_ID  BIGINT       NOT NULL REFERENCES PLANNER_SESSIONS(ID),
    TITLE       VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    CREATED_AT  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    UPDATED_AT  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IDX_PLANNER_APPLIED_ITINERARIES_SESSION_ID ON PLANNER_APPLIED_ITINERARIES(SESSION_ID);