CREATE TABLE HOTELS (
    ID              BIGSERIAL       PRIMARY KEY,
    NAME            VARCHAR(200)    NOT NULL,
    DESCRIPTION     TEXT,
    COUNTRY         VARCHAR(100)    NOT NULL,
    CITY            VARCHAR(100)    NOT NULL,
    ADDRESS         VARCHAR(300),
    LATITUDE        NUMERIC(9,6),
    LONGITUDE       NUMERIC(9,6),
    PRICE_PER_NIGHT NUMERIC(10,2)   NOT NULL,
    STAR_RATING     SMALLINT        NOT NULL CHECK (STAR_RATING BETWEEN 1 AND 5),
    MAIN_IMAGE_URL  VARCHAR(500),
    IS_FEATURED     BOOLEAN         NOT NULL DEFAULT FALSE,
    CREATED_AT      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    UPDATED_AT      TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

CREATE INDEX IDX_HOTELS_CITY    ON HOTELS(CITY);
CREATE INDEX IDX_HOTELS_COUNTRY ON HOTELS(COUNTRY);
CREATE INDEX IDX_HOTELS_PRICE   ON HOTELS(PRICE_PER_NIGHT);
CREATE INDEX IDX_HOTELS_RATING  ON HOTELS(STAR_RATING);

CREATE TABLE HOTEL_AMENITIES (
    HOTEL_ID        BIGINT          NOT NULL REFERENCES HOTELS(ID) ON DELETE CASCADE,
    AMENITY_TYPE    VARCHAR(30)     NOT NULL,
    PRIMARY KEY (HOTEL_ID, AMENITY_TYPE)
);

CREATE TABLE HOTEL_IMAGES (
    ID          BIGSERIAL       PRIMARY KEY,
    HOTEL_ID    BIGINT          NOT NULL REFERENCES HOTELS(ID) ON DELETE CASCADE,
    IMAGE_URL   VARCHAR(500)    NOT NULL,
    SORT_ORDER  INT             NOT NULL DEFAULT 0,
    CREATED_AT  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    UPDATED_AT  TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

CREATE INDEX IDX_HOTEL_IMAGES_HOTEL ON HOTEL_IMAGES(HOTEL_ID);
