CREATE TABLE BOOKINGS
(
    ID               BIGSERIAL       PRIMARY KEY,
    USER_ID          BIGINT          NOT NULL REFERENCES USERS(ID),
    HOTEL_ID         BIGINT          NOT NULL REFERENCES HOTELS(ID),
    CHECK_IN         DATE            NOT NULL,
    CHECK_OUT        DATE            NOT NULL,
    GUEST_COUNT      INTEGER         NOT NULL CHECK (GUEST_COUNT >= 1),
    TOTAL_PRICE      NUMERIC(10, 2)  NOT NULL,
    STATUS           VARCHAR(20)     NOT NULL DEFAULT 'PENDING',
    SPECIAL_REQUESTS TEXT,
    CANCELLED_AT     TIMESTAMPTZ,
    CREATED_AT       TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    UPDATED_AT       TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    CONSTRAINT CHK_CHECKOUT_AFTER_CHECKIN CHECK (CHECK_OUT > CHECK_IN)
);

CREATE INDEX IDX_BOOKINGS_USER_ID ON BOOKINGS(USER_ID);
CREATE INDEX IDX_BOOKINGS_STATUS  ON BOOKINGS(STATUS);
