CREATE TABLE REVIEWS (
    ID          BIGSERIAL       PRIMARY KEY,
    USER_ID     BIGINT          NOT NULL REFERENCES USERS(ID),
    HOTEL_ID    BIGINT          NOT NULL REFERENCES HOTELS(ID),
    RATING      SMALLINT        NOT NULL CHECK (RATING BETWEEN 1 AND 5),
    COMMENT     TEXT,
    CREATED_AT  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    UPDATED_AT  TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

CREATE INDEX IDX_REVIEWS_HOTEL_ID ON REVIEWS(HOTEL_ID);

CREATE TABLE FAVOURITES (
    ID          BIGSERIAL       PRIMARY KEY,
    USER_ID     BIGINT          NOT NULL REFERENCES USERS(ID),
    HOTEL_ID    BIGINT          NOT NULL REFERENCES HOTELS(ID),
    CREATED_AT  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    UPDATED_AT  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    UNIQUE (USER_ID, HOTEL_ID)
);

CREATE INDEX IDX_WISHLIST_USER_ID ON FAVOURITES(USER_ID);
